apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  type: LoadBalancer
  selector:
    app: reverseproxy
  ports:
    - port: 80
      targetPort: 80