apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    service: reverseproxy
